---
- name: Setup AWS CICD stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup output variables
      ansible.builtin.include_vars: vars/output_vars

    - name: Import aws cicd ami setup variables
      ansible.builtin.include_vars: vars/aws-stack-setup

    - name: Import Import VPC setup variables
      ansible.builtin.include_vars: vars/vpc_setup

    - name: Create aws-cicd-stack key pair
      amazon.aws.ec2_key:
        name: awsstack
        region: "{{ region }}"
      register: key_out
    
    - name: Save private key in file awscicd-key.pem
      ansible.builtin.copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./awsstack.pem"
        mode: 0400
      when: key_out.changed

    - name: Create Security Group for Load Balancer
      amazon.aws.ec2_group:
        name: awsELB-SG
        description: Allow port 80 from anywhere IPv4
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: awsELBSG_out

    - name: Create Security Group for AWS CICD stack
      amazon.aws.ec2_group:
        name: awscicdstack-SG
        description: Allow port 22 from bastion-host SG and port 80 anywhere IPv4 awsELB-SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ BastionSGID }}"
          
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ awsELBSG_out.group_id }}"
      register: awscicdstack_out

    - name: Update awscicdstack-SG to talk to its own security group
      amazon.aws.ec2_group:
        name: awscicdstack-SG
        description: Allow all port to communicate within this group.
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ awsELBSG_out.group_id }}"
            


    
