---
- name: Setup awscicd ansible bastion host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/bastion_setup

    - name: Import VPC setup variables
      include_vars: vars/output_vars

    - name: Create a awscicd key
      ec2_key:
        name: awscicd-key
        region: "{{ region }}"
      register: key_out

    - name: Save private key in file awscicd-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./awscicd-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create security group for bastion host
      ec2_group:
        name: bastion-host-sg
        description: Allow port 22 from everywhere and all port within SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules: 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - debug:
        var: BastionSG_out

    - name: Creating Bastion host
      ec2_instance:
        name: "Bastion_host"
        key_name: awscicd-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        state: present
        exact_count: 1
        wait: yes
        wait_timeout: 300
        security_group: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionHost_out