---
- name: Setup awscicd ansible bastion host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup variables
      ansible.builtin.include_vars: vars/vpc_setup

    - name: Import VPC setup variables
      ansible.builtin.include_vars: vars/output_vars

    - name: Create a awscicd key
      amazon.aws.ec2_key:
        name: awscicd-key
        region: "{{ region }}"
      register: key_out

    - name: Save private key in file awscicd-key.pem
      ansible.builtin.copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./awscicd-key.pem"
        mode: 0400
      when: key_out.changed

    - name: Create security group for bastion host
      amazon.aws.ec2_group:
        name: bastion-host-sg
        description: Allow port 22 from everywhere and all port within SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules: 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - ansible.builtin.debug:
        var: BastionSG_out

    - name: Creating Bastion host
      amazon.aws.ec2_instance:
        name: Bastion_host
        key_name: awscicd-key
        image_id: "{{ bastion_ami }}"
        instance_type: t2.micro
        exact_count: 1
        region: "{{ region }}"
        security_group: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
        wait: yes
        tags:
          Project: ansible-aws
          Owner: Devops Team
      register: bastionHost_out
    
    - name: Insert/Update BastionSGID in vars/output_vars
      ansible.builtin.blockinfile:
        path: vars/output_vars
        block: |
          BastionSGId: {{BastionSG_out.group_id}}