---
- name: Generate artifact, copy artifact and sql file to directory
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
  tasks:
    - name: Install git, jdk and maven
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven

    - name: Clone source code from github
      ansible.builtin.git:
        repo: https://github.com/devopshydclub/vprofile-project.git
        dest: ./Vprofile-repo
        version: vp-rem
      register: git_status

    - name: Running mvn install command to build the artifact
      ansible.builtin.command: "mvn install"
      args:
        chdir: Vprofile-repo
      when: git_status.changed
      register: mvn_info

    - name: Copy artifact to files directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: files/ROOT.war
      with_fileglob: Vprofile-repo/target/*.war

    - name: Copy sql file to files directory
      ansible.builtin.copy:
        src: Vprofile-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql 
