---
- name: Setup MySql with accounts db and remotelogin
  hosts: dbsrvgrp
  gather_facts: false
  pre_tasks:
    - name: Update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
  tasks:
    - name: Installing MySql Service and dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: true
      tags:
        - package
    
    - name: Start and Enable mysql Service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true
      tags:
        - svc

    - name: Creating mysql user
      ansible.builtin.mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpass }}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Creating accounts database
      ansible.builtin.mysql_db:
        name: "{{ dbname }}"
        state: present

    - name: Enable remote login to mysql svc
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: true
      notify:
        - Restart mysql
      tags:
        - conf
    
  handlers:
    - name: Restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
