---
- name: Install and setup rabbitmq with user
  hosts: rmqsrvgrp
  gather_facts: false
  tasks:
    - name: Install rabbitmq-server
      ansible.builtin.apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
      tags:
        - package
    
    - name: Add and erlang solution public key
      ansible.builtin.apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
      tags:
        - package

    - name: Install erlang
      ansible.builtin.apt:
        name: erlang
        update_cache: true
        cache_valid_time: 86400
        state: present
      tags:
        - package
    
    - name: Add an Apt signing key, from URL (whichever is available)
      ansible.builtin.apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present
      tags:
        - package
    
    - ansible.builtin.apt_repository:
        repo: deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu jammy main
        state: present
      tags:
        - package
    
    - name: Install rabbitmq server
      ansible.builtin.apt:
        name: rabbitmq-server
        state: present
        update_cache: true
      tags:
        - package

    - name: start and enable rabbitmq service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: true
      tags:
        - svc

    - name: config setup
      ansible.builtin.copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - restart rabbitmq
      tags:
        - conf

    - name: add user and priviliges to it.
      ansible.builtin.rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - restart rabbitmq
      tags:
       - conf

    - name: enable rabbitmq management plugin
      ansible.builtin.rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
      tags:
        - package

  handlers:
    - name: restart rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted