---
- name: Install and setup rabbitmq with user
  hosts: rmqsrvgrp
  gather_facts: false
  tasks:
    - name: Install rabbitmq server
      ansible.builtin.apt:
        name: rabbitmq-server
        state: present
        update_cache: true
      tags:
        - package

    - name: start and enable rabbitmq service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: true
      tags:
        - svc

    - name: config setupweb.yml
      ansible.builtin.copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - restart rabbitmq
      tags:
        - conf

    - name: add user and priviliges to it.
      ansible.builtin.rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - restart rabbitmq
      tags:
       - conf

    - name: enable rabbitmq management plugin
      ansible.builtin.rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
      tags:
        - package

  handlers:
    - name: restart rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted